using System.Data;
using Microsoft.EntityFrameworkCore;
using PUCFinance.AssetManagement.Models;
using PUCFinance.AssetManagement.Services;

namespace PUCFinance.AssetManagement.Data;

public static class DatabaseSeeder
{
    public static async Task SeedAsync(AppDbContext db, ILogger logger)
    {
        await EnsureAuthSchemaAsync(db);
        await RemoveFictitiousDataAsync(db);
        await SeedFundsAsync(db);
        await SeedUsersAsync(db);
        await SeedAssetsAsync(db);

        await db.SaveChangesAsync();
        logger.LogInformation("Database seed verified.");
    }

    private static async Task EnsureAuthSchemaAsync(AppDbContext db)
    {
        if (db.Database.IsNpgsql())
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS teams (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name text NOT NULL UNIQUE,
                    created_at text NOT NULL DEFAULT ((NOW() AT TIME ZONE 'UTC')::text)
                )
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS app_users (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    team_id integer REFERENCES teams(id),
                    name text NOT NULL,
                    email text NOT NULL UNIQUE,
                    password_hash text NOT NULL,
                    role text NOT NULL DEFAULT 'manager',
                    is_active integer NOT NULL DEFAULT 1,
                    created_at text NOT NULL DEFAULT ((NOW() AT TIME ZONE 'UTC')::text)
                )
                """);

            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS team_members (
                    team_id integer NOT NULL REFERENCES teams(id),
                    user_id integer NOT NULL REFERENCES app_users(id),
                    PRIMARY KEY (team_id, user_id)
                )
                """);

            if (!await ColumnExistsAsync(db, "funds", "team_id"))
                await db.Database.ExecuteSqlRawAsync("ALTER TABLE funds ADD COLUMN team_id integer REFERENCES teams(id)");

            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS teams (
                id integer PRIMARY KEY AUTOINCREMENT,
                name text NOT NULL UNIQUE,
                created_at text NOT NULL DEFAULT (datetime('now'))
            )
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS app_users (
                id integer PRIMARY KEY AUTOINCREMENT,
                team_id integer REFERENCES teams(id),
                name text NOT NULL,
                email text NOT NULL UNIQUE,
                password_hash text NOT NULL,
                role text NOT NULL DEFAULT 'manager',
                is_active integer NOT NULL DEFAULT 1,
                created_at text NOT NULL DEFAULT (datetime('now'))
            )
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS team_members (
                team_id integer NOT NULL REFERENCES teams(id),
                user_id integer NOT NULL REFERENCES app_users(id),
                PRIMARY KEY (team_id, user_id)
            )
            """);

        if (!await ColumnExistsAsync(db, "funds", "team_id"))
            await db.Database.ExecuteSqlRawAsync("ALTER TABLE funds ADD COLUMN team_id integer REFERENCES teams(id)");
    }

    private static async Task<bool> ColumnExistsAsync(AppDbContext db, string tableName, string columnName)
    {
        var connection = db.Database.GetDbConnection();
        var shouldClose = connection.State != ConnectionState.Open;
        if (shouldClose)
            await connection.OpenAsync();

        await using var command = connection.CreateCommand();
        command.CommandText = db.Database.IsNpgsql()
            ? """
              SELECT COUNT(*)
              FROM information_schema.columns
              WHERE table_name = @tableName AND column_name = @columnName
              """
            : """
              SELECT COUNT(*)
              FROM pragma_table_info(@tableName)
              WHERE name = @columnName
              """;

        var tableParameter = command.CreateParameter();
        tableParameter.ParameterName = "@tableName";
        tableParameter.Value = tableName;
        command.Parameters.Add(tableParameter);

        var columnParameter = command.CreateParameter();
        columnParameter.ParameterName = "@columnName";
        columnParameter.Value = columnName;
        command.Parameters.Add(columnParameter);

        var result = await command.ExecuteScalarAsync();

        if (shouldClose)
            await connection.CloseAsync();

        return Convert.ToInt32(result) > 0;
    }

    /// <summary>
    /// Remove os fundos e gestores ficticios do MVP (o fundo Beta e o lider continuam).
    /// </summary>
    private static async Task RemoveFictitiousDataAsync(AppDbContext db)
    {
        var fundIds = await db.Funds
            .Where(f => FictitiousFundNames.Contains(f.Name))
            .Select(f => f.Id)
            .ToListAsync();

        if (fundIds.Count > 0)
        {
            await db.PositionHistory.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.RealizedPnl.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.Metrics.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.NavHistory.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.Positions.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.Trades.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.Cash.Where(x => fundIds.Contains(x.FundId)).ExecuteDeleteAsync();
            await db.Funds.Where(f => fundIds.Contains(f.Id)).ExecuteDeleteAsync();
        }

        var userIds = await db.Users
            .Where(u => FictitiousUserEmails.Contains(u.Email))
            .Select(u => u.Id)
            .ToListAsync();

        if (userIds.Count > 0)
        {
            await db.TeamMembers.Where(m => userIds.Contains(m.UserId)).ExecuteDeleteAsync();
            await db.Users.Where(u => userIds.Contains(u.Id)).ExecuteDeleteAsync();
        }

        await db.Teams
            .Where(t => FictitiousTeamNames.Contains(t.Name))
            .Where(t => !db.Funds.Any(f => f.TeamId == t.Id) && !db.Users.Any(u => u.TeamId == t.Id))
            .ExecuteDeleteAsync();
    }

    private static async Task SeedFundsAsync(AppDbContext db)
    {
        var existingTeams = await db.Teams.ToDictionaryAsync(t => t.Name);
        foreach (var seedFund in Funds)
        {
            if (!existingTeams.ContainsKey(seedFund.TeamName))
                db.Teams.Add(new Team { Name = seedFund.TeamName });
        }

        await db.SaveChangesAsync();

        var teams = await db.Teams.ToDictionaryAsync(t => t.Name);
        var existingFunds = await db.Funds.ToDictionaryAsync(f => f.Name);

        foreach (var seedFund in Funds)
        {
            var teamId = teams[seedFund.TeamName].Id;
            if (existingFunds.TryGetValue(seedFund.Name, out var fund))
            {
                fund.TeamId ??= teamId;
                continue;
            }

            db.Funds.Add(new Fund
            {
                Name = seedFund.Name,
                Strategy = seedFund.Strategy,
                InitialCapital = 1_000_000,
                TotalShares = 1_000_000,
                TeamId = teamId
            });
        }

        await db.SaveChangesAsync();

        var funds = await db.Funds.ToListAsync();
        var today = DateTime.Today.ToString("yyyy-MM-dd");

        foreach (var fund in funds)
        {
            if (!await db.Cash.AnyAsync(c => c.FundId == fund.Id))
            {
                db.Cash.Add(new Cash
                {
                    FundId = fund.Id,
                    Balance = fund.InitialCapital
                });
            }

            if (!await db.NavHistory.AnyAsync(n => n.FundId == fund.Id))
            {
                db.NavHistory.Add(new NavHistory
                {
                    FundId = fund.Id,
                    Date = today,
                    TotalEquity = fund.InitialCapital,
                    TotalShares = fund.TotalShares,
                    ShareValue = fund.TotalShares > 0 ? fund.InitialCapital / fund.TotalShares : 0,
                    DailyReturn = 0,
                    CashBalance = fund.InitialCapital
                });
            }
        }
    }

    private static async Task SeedUsersAsync(AppDbContext db)
    {
        var passwordService = new PasswordService();
        await MigrateLegacyLeaderAsync(db, passwordService);
        await EnsureLeaderAsync(db, passwordService);

        // Gestores entram so com o login, sem senha
        foreach (var manager in Managers)
            await AddUserIfMissingAsync(db, manager.Name, manager.Email, string.Empty, AppRoles.Manager);

        await db.SaveChangesAsync();

        var users = await db.Users.ToDictionaryAsync(u => u.Email);
        var teams = await db.Teams.ToDictionaryAsync(t => t.Name);
        var existingMemberships = (await db.TeamMembers
            .Select(m => new { m.TeamId, m.UserId })
            .ToListAsync())
            .Select(m => (m.TeamId, m.UserId))
            .ToHashSet();

        foreach (var seedFund in Funds)
        {
            var teamId = teams[seedFund.TeamName].Id;
            foreach (var email in seedFund.MemberEmails)
            {
                var userId = users[email].Id;
                if (existingMemberships.Add((teamId, userId)))
                    db.TeamMembers.Add(new TeamMember { TeamId = teamId, UserId = userId });
            }
        }
    }

    /// <summary>
    /// Converte o lider do MVP (lider@pucfinance.local / senha publica) no lider real,
    /// preservando o mesmo usuario.
    /// </summary>
    private static async Task MigrateLegacyLeaderAsync(AppDbContext db, PasswordService passwordService)
    {
        var legacyLeader = await db.Users.FirstOrDefaultAsync(u => u.Email == LegacyLeaderEmail);
        if (legacyLeader == null || await db.Users.AnyAsync(u => u.Email == Leader.Email))
            return;

        legacyLeader.Name = Leader.Name;
        legacyLeader.Email = Leader.Email;
        legacyLeader.PasswordHash = passwordService.HashPassword(LeaderPassword);
        legacyLeader.Role = AppRoles.Leader;
        await db.SaveChangesAsync();
    }

    private static async Task EnsureLeaderAsync(AppDbContext db, PasswordService passwordService)
    {
        var leader = await db.Users.FirstOrDefaultAsync(u => u.Email == Leader.Email);
        if (leader == null)
        {
            await AddUserIfMissingAsync(db, Leader.Name, Leader.Email,
                passwordService.HashPassword(LeaderPassword), AppRoles.Leader);
            return;
        }

        // Senha do lider da versao anterior volta a ser a senha padrao
        if (leader.PasswordHash == SupersededLeaderPasswordHash)
            leader.PasswordHash = passwordService.HashPassword(LeaderPassword);
    }

    private static async Task AddUserIfMissingAsync(
        AppDbContext db,
        string name,
        string email,
        string passwordHash,
        string role)
    {
        if (await db.Users.AnyAsync(u => u.Email == email))
            return;

        db.Users.Add(new AppUser
        {
            Name = name,
            Email = email,
            PasswordHash = passwordHash,
            Role = role,
            IsActive = 1
        });
    }

    private static readonly string[] FictitiousFundNames = ["Alpha", "Gamma"];
    private static readonly string[] FictitiousTeamNames = ["Alpha Team", "Gamma Team"];
    private static readonly string[] FictitiousUserEmails =
    [
        "alpha@pucfinance.local",
        "beta@pucfinance.local",
        "gamma@pucfinance.local"
    ];

    private sealed record SeedUser(string Name, string Email);

    private const string LegacyLeaderEmail = "lider@pucfinance.local";
    private const string LeaderPassword = "Admin@123";
    private const string SupersededLeaderPasswordHash =
        "pbkdf2$100000$9BUCxwF2kPYOHPLgEZvEVg==$m48eT9Osy90xmk9suQ8T9eHVZa9xCkkutGP8mPSWpcA=";
    private static readonly SeedUser Leader = new("Gustavo", "gustavo@pucfinance");

    private static readonly SeedUser[] Managers =
    [
        new("Luigi", "luigi@pucfinance"),
        new("Braguinha", "braguinha@pucfinance"),
        new("Cathe", "cathe@pucfinance"),
        new("Italo", "italo@pucfinance"),
        new("Helena", "helena@pucfinance"),
        new("Bruna", "bruna@pucfinance"),
        new("Thomas", "thomas@pucfinance")
    ];

    private sealed record SeedFund(string Name, string? Strategy, string TeamName, string[] MemberEmails);

    private static readonly SeedFund[] Funds =
    [
        // Fundo de teste mantido do MVP, sem gestores (so o lider acessa)
        new("Beta", "Long/Short", "Beta Team", []),

        new("Renda Variável (Long & Short)", null, "Renda Variável (Long & Short)",
            ["luigi@pucfinance", "braguinha@pucfinance"]),
        new("Renda Variável (Value Investing)", null, "Renda Variável (Value Investing)",
            ["cathe@pucfinance", "italo@pucfinance"]),
        new("Best Ideas (Multimercado)", null, "Best Ideas (Multimercado)",
            [
                "luigi@pucfinance", "braguinha@pucfinance", "cathe@pucfinance",
                "italo@pucfinance", "helena@pucfinance", "bruna@pucfinance",
                "thomas@pucfinance"
            ]),
        new("Renda Fixa (On shore & Off shore)", null, "Renda Fixa (On shore & Off shore)",
            ["braguinha@pucfinance", "helena@pucfinance"]),
        new("Multimercado (Raiz)", null, "Multimercado (Raiz)",
            ["bruna@pucfinance", "thomas@pucfinance"])
    ];

    private static async Task SeedAssetsAsync(AppDbContext db)
    {
        var existingTickers = (await db.Assets
            .Select(a => a.Ticker)
            .ToListAsync())
            .ToHashSet();

        foreach (var asset in Assets)
        {
            if (existingTickers.Contains(asset.Ticker))
                continue;

            db.Assets.Add(new Asset
            {
                Ticker = asset.Ticker,
                Name = asset.Name,
                AssetClass = asset.AssetClass,
                Sector = asset.Sector,
                Exchange = asset.Exchange,
                Currency = asset.Currency,
                YahooTicker = asset.YahooTicker,
                IsActive = 1
            });
        }
    }

    private sealed record SeedAsset(
        string Ticker,
        string Name,
        string AssetClass,
        string Sector,
        string Exchange,
        string Currency,
        string? YahooTicker = null);

    private static readonly SeedAsset[] Assets =
    [
        new("PETR4", "Petrobras PN", "equity_br", "Petroleo e Gas", "B3", "BRL"),
        new("VALE3", "Vale ON", "equity_br", "Mineracao", "B3", "BRL"),
        new("ITUB4", "Itau Unibanco PN", "equity_br", "Bancos", "B3", "BRL"),
        new("BBDC4", "Bradesco PN", "equity_br", "Bancos", "B3", "BRL"),
        new("BBAS3", "Banco do Brasil ON", "equity_br", "Bancos", "B3", "BRL"),
        new("WEGE3", "WEG ON", "equity_br", "Bens Industriais", "B3", "BRL"),
        new("ABEV3", "Ambev ON", "equity_br", "Bebidas", "B3", "BRL"),
        new("RENT3", "Localiza ON", "equity_br", "Aluguel de Carros", "B3", "BRL"),
        new("MGLU3", "Magazine Luiza ON", "equity_br", "Varejo", "B3", "BRL"),
        new("SUZB3", "Suzano ON", "equity_br", "Papel e Celulose", "B3", "BRL"),
        new("JBSS3", "JBS ON", "equity_br", "Alimentos", "B3", "BRL"),
        new("ELET3", "Eletrobras ON", "equity_br", "Energia Eletrica", "B3", "BRL"),
        new("B3SA3", "B3 ON", "equity_br", "Servicos Financeiros", "B3", "BRL"),
        new("RDOR3", "Rede D Or ON", "equity_br", "Saude", "B3", "BRL"),
        new("EMBR3", "Embraer ON", "equity_br", "Aeronautica", "B3", "BRL"),
        new("CYRE3", "Cyrela ON", "equity_br", "Construcao", "B3", "BRL"),
        new("VIVT3", "Telefonica Brasil ON", "equity_br", "Telecomunicacoes", "B3", "BRL"),
        new("HAPV3", "Hapvida ON", "equity_br", "Saude", "B3", "BRL"),
        new("CSAN3", "Cosan ON", "equity_br", "Energia", "B3", "BRL"),
        new("PRIO3", "PRIO ON", "equity_br", "Petroleo e Gas", "B3", "BRL"),

        new("BOVA11", "iShares Ibovespa", "etf", "Indice", "B3", "BRL"),
        new("IVVB11", "iShares S&P 500 BRL", "etf", "Indice", "B3", "BRL"),
        new("SMAL11", "iShares Small Cap", "etf", "Indice", "B3", "BRL"),
        new("HASH11", "Hashdex Crypto", "etf", "Cripto", "B3", "BRL"),
        new("IMAB11", "Itau IMA-B", "etf", "Renda Fixa", "B3", "BRL"),

        new("AAPL", "Apple", "equity_us", "Tecnologia", "NASDAQ", "USD", "AAPL"),
        new("MSFT", "Microsoft", "equity_us", "Tecnologia", "NASDAQ", "USD", "MSFT"),
        new("NVDA", "NVIDIA", "equity_us", "Tecnologia", "NASDAQ", "USD", "NVDA"),
        new("AMZN", "Amazon", "equity_us", "Tecnologia", "NASDAQ", "USD", "AMZN"),
        new("GOOGL", "Alphabet", "equity_us", "Tecnologia", "NASDAQ", "USD", "GOOGL"),
        new("TSLA", "Tesla", "equity_us", "Automotivo", "NASDAQ", "USD", "TSLA"),
        new("META", "Meta Platforms", "equity_us", "Tecnologia", "NASDAQ", "USD", "META"),
        new("JPM", "JPMorgan Chase", "equity_us", "Bancos", "NYSE", "USD", "JPM"),

        new("USDBRL", "Dolar/Real", "fx", "Cambio", "FX", "BRL", "USDBRL=X"),
        new("EURBRL", "Euro/Real", "fx", "Cambio", "FX", "BRL", "EURBRL=X"),
        new("EURUSD", "Euro/Dolar", "fx", "Cambio", "FX", "USD", "EURUSD=X"),
        new("USDJPY", "Dolar/Iene", "fx", "Cambio", "FX", "JPY", "JPY=X"),

        new("CL", "Petroleo WTI", "commodity", "Energia", "NYMEX", "USD", "CL=F"),
        new("GC", "Ouro", "commodity", "Metais Preciosos", "COMEX", "USD", "GC=F"),
        new("SI", "Prata", "commodity", "Metais Preciosos", "COMEX", "USD", "SI=F"),
        new("NG", "Gas Natural", "commodity", "Energia", "NYMEX", "USD", "NG=F"),
        new("ZS", "Soja", "commodity", "Agricultura", "CBOT", "USD", "ZS=F"),
        new("ZC", "Milho", "commodity", "Agricultura", "CBOT", "USD", "ZC=F"),

        new("BTC", "Bitcoin", "crypto", "Cripto", "Global", "USD", "BTC-USD"),
        new("ETH", "Ethereum", "crypto", "Cripto", "Global", "USD", "ETH-USD"),
        new("SOL", "Solana", "crypto", "Cripto", "Global", "USD", "SOL-USD")
    ];
}
